services:
  marcossantiago-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: marcossantiago-web:latest
    container_name: marcossantiago-web
    restart: unless-stopped
    ports:
      - "3010:80"

  marcossantiago-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    image: marcossantiago-bot:latest
    container_name: marcossantiago-bot
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
